//Generated by OpenAI API at 12/09/2023
export const LOS_CAPRICHOS = [
	{
		filename: "capricho_one",
		name: "Francisco Goya y Lucientes, Pintor",
		translation: "Francisco Goya and Lucientes, the Painter",
		description: "This plate serves as a self-portrait of Francisco Goya and introduces the theme of the artist's dream, a recurring motif in the series. It reflects Goya's anxieties and the need to express his critical views during a time of political and social turmoil in Spain."
	},
	{
		filename: "capricho_two",
		name: "El sí pronuncian y la mano alargan al primero que llega",
		translation: "They say 'yes' and extend the hand to the first who arrives",
		description: "Goya satirizes the practice of arranged marriages, highlighting the lack of agency and choice for young women in such arrangements. This commentary is relevant to the societal norms and gender roles prevalent in 18th-century Spain."
	},
	{
		filename: "capricho_three",
		name: "Que viene el Coco",
		translation: "Here comes the Bogeyman",
		description: "This plate addresses irrational fears and the power of superstition, featuring a woman warning her child about the Bogeyman. It reflects the widespread superstitions and anxieties of the time, including fear of the unknown."
	},
	{
		filename: "capricho_four",
		name: "El que dirá el bobo",
		translation: "What the fool will say",
		description: "Goya explores themes of gossip and judgment, suggesting that the simpleton's opinions can be as impactful as others'. This commentary reflects the gossip-driven society and the power of public opinion in the 18th century."
	},
	{
		filename: "capricho_five",
		name: "El mismo burro",
		translation: "The same donkey",
		description: "This plate uses satire to comment on the repetitive and unchanging nature of certain societal behaviors. It reflects Goya's critique of societal stagnation and rigidity during his era."
	},
	{
		filename: "capricho_six",
		name: "El hechizado por fuerza",
		translation: "The one bewitched by force",
		description: "Goya depicts a man suffering from the effects of a spell or curse, critiquing irrational beliefs and superstitions. This reflects the prevalence of superstition and the fear of the supernatural in 18th-century Spain."
	},
	{
		filename: "capricho_seven",
		name: "Tal para cual",
		translation: "Birds of a feather",
		description: "In this print, Goya portrays people who are similar in character, suggesting that like-minded individuals tend to flock together. It reflects the social divisions and cliques present in Spanish society at the time."
	},
	{
		filename: "capricho_eight",
		name: "Los resultados",
		translation: "The results",
		description: "This plate hints at the consequences of certain actions or decisions, symbolized by a giant floating head. It reflects the uncertainty and unpredictability of the outcomes of political and personal choices during Goya's time."
	},
	{
		filename: "capricho_nine",
		name: "Nadie se conoce",
		translation: "Nobody knows themselves",
		description: "Goya explores the idea that people may not fully understand themselves, represented by a man looking into a mirror. It reflects the introspection and self-examination encouraged by the Enlightenment ideals of the era."
	},
	{
		filename: "capricho_ten",
		name: "El amor y la muerte",
		translation: "Love and death",
		description: "This plate contrasts the themes of love and death, symbolized by two figures riding a donkey. It reflects the juxtaposition of romanticism and mortality in the cultural and philosophical discourse of the time."
	}
];

